import { describe, expect, it } from "vitest";
import { isPickable } from "@/lib/blanks/catalog";
import { readSeedCatalog } from "@/lib/blanks/seed-files";
import { DEFAULT_FIT_DEFAULTS, toFitSettings } from "@/lib/fit-defaults-preference";
import { boardOnBlank, fitAt, prepareBlank } from "@/lib/geometry/blank-fit";
import { DEFAULT_FOIL_SPEC } from "@/lib/geometry/foil";
import { BOARD_PRESETS, type BoardPreset } from "@/lib/geometry/presets";
import { DEFAULT_FALLBACK_ROCKER } from "@/lib/geometry/rocker";
import { inchesToMm, mm } from "@/lib/geometry/units";
import { boardBlankSchema } from "@/lib/models/design-snapshot";
import {
  PRESET_BLANKS,
  presetBlank,
  presetDesignFields,
  presetFitContext,
  provisionalPresetPick,
} from "./preset-blanks";

/**
 * The drift guard for `preset-blanks.generated.json` (T-11-29, RESEARCH Pitfall 4). The module is
 * written only by `scripts/generate-preset-blanks.ts`; every expectation here is read from the
 * committed catalogue CSVs through the tested reader or recomputed by the rule — never typed.
 */

const CATALOGUE = readSeedCatalog();
const PREPARED = CATALOGUE.filter(isPickable).map(prepareBlank);
const SETTINGS = toFitSettings(DEFAULT_FIT_DEFAULTS);
const keyOf = (record: { vendor: string; name: string }) => `${record.vendor}\u0000${record.name}`;

describe("preset-blanks.generated.json — generated, and identical to the catalogue", () => {
  it("says it is generated, and has a pick for exactly the four presets", () => {
    expect(PRESET_BLANKS.note).toContain("GENERATED by scripts/generate-preset-blanks.ts");
    expect(Object.keys(PRESET_BLANKS.picks).sort()).toEqual(BOARD_PRESETS.map((preset) => preset.id).sort());
  });

  it("holds exactly the picked blanks — no more, no fewer — sorted by vendor then name", () => {
    const pickedKeys = new Set(Object.values(PRESET_BLANKS.picks).map(keyOf));
    const moduleKeys = PRESET_BLANKS.blanks.map(keyOf);
    expect(new Set(moduleKeys)).toEqual(pickedKeys);
    expect(moduleKeys.length).toBe(pickedKeys.size);
    const sorted = [...PRESET_BLANKS.blanks].sort((a, b) =>
      a.vendor !== b.vendor ? (a.vendor < b.vendor ? -1 : 1) : a.name < b.name ? -1 : 1,
    );
    expect(PRESET_BLANKS.blanks.map(keyOf)).toEqual(sorted.map(keyOf));
  });

  it("every blank in the module deep-equals its rows read from the CSVs, and is pickable", () => {
    for (const record of PRESET_BLANKS.blanks) {
      const fromCsv = CATALOGUE.find((blank) => keyOf(blank) === keyOf(record));
      expect(fromCsv, `${record.vendor} ${record.name} is not in the catalogue`).toBeDefined();
      expect(record).toEqual(fromCsv);
      expect(isPickable(record)).toBe(true);
    }
  });

  it.each(BOARD_PRESETS)("$id: a provisional pick is exactly what the rule picks from the catalogue today", (preset) => {
    const pick = PRESET_BLANKS.picks[preset.id];
    if (preset.blank) {
      // A captured pick: the module records it as the founder's, not the rule's.
      expect(pick).toEqual({
        vendor: preset.blank.vendor,
        name: preset.blank.name,
        placementMm: preset.blank.placement,
        provisional: false,
      });
      return;
    }
    expect(pick.provisional).toBe(true);
    expect(provisionalPresetPick(preset, PREPARED)).toEqual(pick);
  });
});

describe("the rule and the picks (D-03, D-08)", () => {
  it.each(BOARD_PRESETS)("$id: its blank fits the preset's own board at its placement, with the default fit settings", (preset) => {
    const blank = presetBlank(preset);
    const ctx = presetFitContext(preset);
    const result = fitAt(
      boardOnBlank(prepareBlank(blank.copy), ctx.board, blank.placement),
      ctx.halfWidthAt,
      ctx.widePointStation,
      SETTINGS.widthMargin,
    );
    expect(result.fits).toBe(true);
  });

  it.each(BOARD_PRESETS)("$id: the rule's pick is a fitting blank at least Extra Length longer than the board", (preset) => {
    const pick = provisionalPresetPick(preset, PREPARED);
    const record = CATALOGUE.find((blank) => keyOf(blank) === keyOf(pick))!;
    expect(record.lengthMm).toBeGreaterThanOrEqual(preset.outline.length + SETTINGS.extraLength - 1e-6);
  });

  it("names the preset when nothing in the catalogue fits it", () => {
    const shortboard = BOARD_PRESETS.find((preset) => preset.id === "shortboard")!;
    expect(() => provisionalPresetPick(shortboard, [])).toThrow(/Shortboard/);
  });

  it("the fit context is the preset's own board: its length, centre and tips, no fine-tunes", () => {
    for (const preset of BOARD_PRESETS) {
      const { board } = presetFitContext(preset);
      expect(board).toEqual({
        length: preset.outline.length,
        centerThickness: preset.foil.center,
        noseTip: preset.foil.noseTip,
        tailTip: preset.foil.tailTip,
        nose12Offset: 0,
        tail12Offset: 0,
      });
    }
  });
});

describe("presetBlank and presetDesignFields — what a preset opens as", () => {
  it.each(BOARD_PRESETS)("$id: opens in the module's copy of its blank, at its pick's placement, with zero fine-tunes", (preset) => {
    const pick = PRESET_BLANKS.picks[preset.id];
    const fields = presetDesignFields(preset);
    const record = PRESET_BLANKS.blanks.find((blank) => keyOf(blank) === keyOf(pick))!;
    // The very same object, so the store prepares it once however often the preset is applied.
    expect(fields.blank.copy).toBe(record);
    expect(fields.blank.placement).toBe(pick.placementMm);
    expect(fields.blank.nose12Offset).toBe(0);
    expect(fields.blank.tail12Offset).toBe(0);
  });

  it.each(BOARD_PRESETS)("$id: keeps its centre and tips, the default hand-set rocker, and the default 12\" fallbacks", (preset) => {
    const fields = presetDesignFields(preset);
    expect(fields.rocker).toEqual(DEFAULT_FALLBACK_ROCKER);
    expect(fields.foil.noseTip).toBe(preset.foil.noseTip);
    expect(fields.foil.center).toBe(preset.foil.center);
    expect(fields.foil.tailTip).toBe(preset.foil.tailTip);
    expect(fields.foil.nose12).toBe(DEFAULT_FOIL_SPEC.nose12);
    expect(fields.foil.tail12).toBe(DEFAULT_FOIL_SPEC.tail12);
    expect(fields.outline).toBe(preset.outline);
    expect(fields.rails).toBe(preset.rails);
    expect(fields.fins).toBe(preset.fins);
  });

  it.each(BOARD_PRESETS)("$id: its blank sits inside the saved-board (version 4) limits, so a preset board can be saved", (preset) => {
    expect(boardBlankSchema.safeParse(presetBlank(preset)).success).toBe(true);
  });

  it("a captured blank line wins over the provisional pick", () => {
    const fish = BOARD_PRESETS.find((preset) => preset.id === "fish")!;
    // Capture the SHORTBOARD's blank into the fish, a quarter-inch toward the nose — any blank the
    // module holds will do; the point is which one wins.
    const other = PRESET_BLANKS.picks.shortboard;
    const captured: BoardPreset = {
      ...fish,
      blank: { vendor: other.vendor, name: other.name, placement: inchesToMm(0.25) },
    };
    const blank = presetBlank(captured);
    expect(keyOf(blank.copy)).toBe(keyOf(other));
    expect(blank.placement).toBe(inchesToMm(0.25));
  });

  it("a captured blank the module does not hold fails loudly, naming the fix", () => {
    const fish = BOARD_PRESETS.find((preset) => preset.id === "fish")!;
    const captured: BoardPreset = { ...fish, blank: { vendor: "Nobody", name: "Nothing", placement: mm(0) } };
    expect(() => presetBlank(captured)).toThrow(/generate-preset-blanks/);
  });
});
