/**
 * Phase 11's foil, kept ONLY to carry boards saved under Phase 11 across to Phase 12's cut
 * (Phase 12 D-07/D-14) — the same spirit as `bezierToFiveStations` in `rocker.ts`, old maths kept
 * alive solely to read an old save.
 *
 * Phase 11 scaled the blank's own thickness by one ratio — the target centre ÷ the blank's
 * thickness under the board's centre (Phase 11 D-18) — so every station's thickness was that
 * fraction of the blank's there, eased into the tip settings over the last 12" and held at or above
 * each tip's setting inside that window. Phase 12 replaces that with a planer's cut (a deck skin, a
 * bottom parallel to the blank's, tips thinned last), and a Phase 11 board reopens with its five
 * station numbers exactly as they were by letting its two 12" fine-tunes absorb the difference.
 *
 * This file is pinned by `__fixtures__/phase11-foil-golden.json`, which
 * `scripts/extract-phase11-foil-golden.ts` generated by running tag v1.3's own `boardOnBlank`
 * before Phase 12 touched it. Its only caller outside tests is `lib/models/design-snapshot.ts`,
 * through `carryPhase11Blank`.
 *
 * No React/browser/database import — pure geometry (CLAUDE.md Rule 1). Every length is millimetres.
 */
import { DEFAULT_BLANK_CUT, type BlankCut, type TipStyle } from "./blank";
import {
  blankStationOf,
  boardOnBlank,
  clampPlacement,
  FIT_EPSILON_MM,
  prepareBlankPchip,
  TIP_EASE_WINDOW_MM,
  type PreparedBlank,
} from "./blank-fit";
import { mm, type Mm } from "./units";

/** The board settings Phase 11's foil read: its length, target centre, two tips and two tweaks. */
export interface Phase11Board {
  length: Mm;
  centerThickness: Mm;
  noseTip: Mm;
  tailTip: Mm;
  nose12Offset: Mm;
  tail12Offset: Mm;
}

/**
 * The thickness Phase 11 showed at one 12" station, fine-tune included — exactly what tag v1.3's
 * `boardOnBlank(...).thicknessAt` returned there.
 *
 * At a 12" station Phase 11's tip ease weighs nothing, so the foil there was the blank's thickness
 * times the ratio. Its never-below-the-tip guard ran twice — once on the derived value and again
 * after the fine-tune was added — which is why the tip setting appears in two nested `max`es.
 * Where the board runs past the blank the blank's thickness reads 0, as it did in Phase 11.
 *
 * Phase 11's number is read on today's curve whatever the live rule is (Phase 14 D-25, SPEC
 * constraint 5): the blank is prepared again here with `prepareBlankPchip`, from the record the
 * caller's blank was fitted to, so editing the live rule in `prepareBlank` cannot move a Phase 11
 * board's number.
 */
export function phase11TwelveInch(
  prepared: PreparedBlank,
  board: Phase11Board,
  placement: Mm,
  station: "tail12" | "nose12",
): Mm {
  const frozen = prepareBlankPchip(prepared.record);
  const L = board.length;
  const Lb = frozen.lengthMm;
  const p = clampPlacement(placement, Lb, L);
  const blankThicknessAt = (s: number) => {
    const u = blankStationOf(mm(s), p, L, Lb);
    return u >= -FIT_EPSILON_MM && u <= Lb + FIT_EPSILON_MM ? frozen.thickness.sample(u) : 0;
  };
  const underCentre = blankThicknessAt(L / 2);
  const ratio = underCentre > 0 ? board.centerThickness / underCentre : 0;
  const s = station === "tail12" ? TIP_EASE_WINDOW_MM : L - TIP_EASE_WINDOW_MM;
  const tip = station === "tail12" ? board.tailTip : board.noseTip;
  const offset = station === "tail12" ? board.tail12Offset : board.nose12Offset;
  return mm(Math.max(Math.max(ratio * blankThicknessAt(s), tip) + offset, tip));
}

/**
 * Carries a board saved under Phase 11 across to Phase 12's cut (D-07, D-14): the out-of-the-box
 * deck skin, the Tip Style passed in (the shaper's account default), fine-tunes on the Deck — and
 * the two 12" fine-tunes set to whatever makes each 12" station read exactly what Phase 11 showed
 * there. The tips and the centre need nothing: both models put the tips on their settings and the
 * centre on the target. So the five station thicknesses a shaper saw come back unchanged; only the
 * curve between them follows the new cut.
 *
 * The new 12" thickness is read off ONE `boardOnBlank` with this cut and no fine-tune — never a
 * second thickness formula. The offsets are returned unclamped; the snapshot owns its own bound.
 *
 * As the founder accepted (D-14): some carried boards open flagged "doesn't fit" (the deck at a 12"
 * station can rise above the blank's deck once the tweak is bigger than the skin), and under Pin
 * deck the tip rockers can move.
 */
export function carryPhase11Blank(
  prepared: PreparedBlank,
  board: Phase11Board,
  placement: Mm,
  tipStyle: TipStyle,
): BlankCut & { nose12Offset: Mm; tail12Offset: Mm } {
  const cut: BlankCut = { deckSkin: DEFAULT_BLANK_CUT.deckSkin, tipStyle, fineTuneSurface: "deck" };
  const untuned = boardOnBlank(
    prepared,
    {
      length: board.length,
      centerThickness: board.centerThickness,
      noseTip: board.noseTip,
      tailTip: board.tailTip,
      nose12Offset: mm(0),
      tail12Offset: mm(0),
      ...cut,
    },
    placement,
  );
  const L = board.length;
  return {
    ...cut,
    nose12Offset: mm(
      phase11TwelveInch(prepared, board, placement, "nose12") - untuned.derivedThicknessAt(L - TIP_EASE_WINDOW_MM),
    ),
    tail12Offset: mm(
      phase11TwelveInch(prepared, board, placement, "tail12") - untuned.derivedThicknessAt(TIP_EASE_WINDOW_MM),
    ),
  };
}
