/**
 * Phase 11's foil, kept ONLY to carry boards saved under Phase 11 across to Phase 12's cut
 * (Phase 12 D-07/D-14) — the same spirit as `bezierToFiveStations` in `rocker.ts`, old maths kept
 * alive solely to read an old save.
 *
 * Phase 11 scaled the blank's own thickness by one ratio — the target centre ÷ the blank's
 * thickness under the board's centre (Phase 11 D-18) — so every station's thickness was that
 * fraction of the blank's there, eased into the tip settings over the last 12" and held at or above
 * each tip's setting inside that window. Phase 12 replaces that with a planer's cut (a deck skin, a
 * bottom parallel to the blank's, tips thinned last), and a Phase 11 board reopens with its five
 * station numbers exactly as they were by letting its two 12" fine-tunes absorb the difference.
 *
 * This file is pinned by `__fixtures__/phase11-foil-golden.json`, which
 * `scripts/extract-phase11-foil-golden.ts` generated by running tag v1.3's own `boardOnBlank`
 * before Phase 12 touched it. Its only caller outside tests is `lib/models/design-snapshot.ts`.
 *
 * No React/browser/database import — pure geometry (CLAUDE.md Rule 1). Every length is millimetres.
 */
import {
  blankStationOf,
  clampPlacement,
  FIT_EPSILON_MM,
  TIP_EASE_WINDOW_MM,
  type PreparedBlank,
} from "./blank-fit";
import { mm, type Mm } from "./units";

/** The board settings Phase 11's foil read: its length, target centre, two tips and two tweaks. */
export interface Phase11Board {
  length: Mm;
  centerThickness: Mm;
  noseTip: Mm;
  tailTip: Mm;
  nose12Offset: Mm;
  tail12Offset: Mm;
}

/**
 * The thickness Phase 11 showed at one 12" station, fine-tune included — exactly what tag v1.3's
 * `boardOnBlank(...).thicknessAt` returned there.
 *
 * At a 12" station Phase 11's tip ease weighs nothing, so the foil there was the blank's thickness
 * times the ratio. Its never-below-the-tip guard ran twice — once on the derived value and again
 * after the fine-tune was added — which is why the tip setting appears in two nested `max`es.
 * Where the board runs past the blank the blank's thickness reads 0, as it did in Phase 11.
 */
export function phase11TwelveInch(
  prepared: PreparedBlank,
  board: Phase11Board,
  placement: Mm,
  station: "tail12" | "nose12",
): Mm {
  const L = board.length;
  const Lb = prepared.lengthMm;
  const p = clampPlacement(placement, Lb, L);
  const blankThicknessAt = (s: number) => {
    const u = blankStationOf(mm(s), p, L, Lb);
    return u >= -FIT_EPSILON_MM && u <= Lb + FIT_EPSILON_MM ? prepared.thickness.sample(u) : 0;
  };
  const underCentre = blankThicknessAt(L / 2);
  const ratio = underCentre > 0 ? board.centerThickness / underCentre : 0;
  const s = station === "tail12" ? TIP_EASE_WINDOW_MM : L - TIP_EASE_WINDOW_MM;
  const tip = station === "tail12" ? board.tailTip : board.noseTip;
  const offset = station === "tail12" ? board.tail12Offset : board.nose12Offset;
  return mm(Math.max(Math.max(ratio * blankThicknessAt(s), tip) + offset, tip));
}
