import { isWellFormedBlankRecord } from "@/lib/blanks/catalog";
import type { BlankRecord, BlankShortfall } from "../blank";
import type { RockerStationKey } from "../rocker";
import golden from "./phase14-today-golden.json";

/**
 * Today's numbers, pinned from the live site's code (commit ed39f4a) before Phase 14 changes how a
 * blank's curves are drawn (D-26) — generated by `scripts/extract-phase14-today-golden.ts`, never
 * hand-edited. Every blank the pin was recorded on is carried in it by value (`blanks`), and the
 * tests rebuild those blanks from here (`pinnedBlank`, `pinnedCatalogue`) and never from today's
 * catalogue: a catalogue correction is a data change, and must not be able to move a number recorded
 * on the old data. Test-only: nothing outside the test suites and the pin's tests imports this file.
 */

type FiveStations = Record<RockerStationKey, number>;

export interface Phase14CurvePoint {
  x: number;
  y: number;
}

export interface Phase14SweepPoint {
  s: number;
  rocker: number;
  thickness: number;
}

export interface Phase14HiddenEntry {
  vendor: string;
  name: string;
  /** How many blanks carried exactly this curve (kept and hidden values identical); this is the first. */
  mergedCount: number;
  kept: { label: string; x: number; y: number }[];
  hidden: { label: string; x: number; printed: number; pchip: number }[];
}

export interface Phase14Today {
  provenance: string;
  commit: string;
  blanks: BlankRecord[];
  curves: {
    vendor: string;
    name: string;
    /** Levelled bottom: each printed station, then each interval's midpoint. */
    rocker: Phase14CurvePoint[];
    thickness: Phase14CurvePoint[];
    width: Phase14CurvePoint[];
  }[];
  presets: {
    id: string;
    vendor: string;
    name: string;
    placementMm: number;
    boardLengthMm: number;
    thicknessMm: FiveStations;
    rockerMm: FiveStations;
    litres: number;
    sweep: Phase14SweepPoint[];
  }[];
  handSet: {
    boardLengthMm: number;
    thicknessMm: FiveStations;
    rockerMm: FiveStations;
    litres: number;
    sweep: Phase14SweepPoint[];
  };
  stress: {
    label: string;
    vendor: string;
    name: string;
    boardLengthMm: number;
    centerThicknessMm: number;
    placementMm: number;
    buildable: boolean;
    thicknessMm: FiveStations;
    rockerMm: FiveStations;
    fits: boolean;
    worst: BlankShortfall;
  }[];
  hiddenStations: Record<"rocker" | "thickness" | "width", Phase14HiddenEntry[]>;
}

/** The parsed fixture, typed (JSON imports type every number as a plain number). */
export const PHASE14_TODAY: Phase14Today = golden as unknown as Phase14Today;

/** A fresh copy of one pinned row, checked to be a well-formed blank record. */
function freshRecord(row: unknown): BlankRecord {
  const record: unknown = JSON.parse(JSON.stringify(row));
  if (!isWellFormedBlankRecord(record)) {
    throw new Error("A blank in phase14-today-golden.json is not a well-formed blank record — re-run the generator.");
  }
  return record;
}

/** Every blank of the catalogue as the pin was recorded on it, in catalogue order — new objects each call. */
export function pinnedCatalogue(): BlankRecord[] {
  return PHASE14_TODAY.blanks.map(freshRecord);
}

/** One pinned blank by vendor and name — a new object each call; throws when the pin does not carry it. */
export function pinnedBlank(vendor: string, name: string): BlankRecord {
  const row = PHASE14_TODAY.blanks.find((blank) => blank.vendor === vendor && blank.name === name);
  if (!row) {
    throw new Error(
      `${vendor} ${name} is not in phase14-today-golden.json — re-run scripts/extract-phase14-today-golden.ts`,
    );
  }
  return freshRecord(row);
}
