/**
 * GENERATED FILE PRODUCER — writes lib/geometry/__fixtures__/phase11-foil-golden-blanks.json: the
 * foam blanks that Phase 11's recorded boards (lib/geometry/__fixtures__/phase11-foil-golden.json)
 * sit on, exactly as the catalogue held them when those numbers were recorded. The output is
 * generated and must never be hand-edited; re-run this script.
 *
 *   npx --no-install tsx --tsconfig ./tsconfig.json scripts/extract-phase11-golden-blanks.ts
 *
 * run from the repository root. (D-20: nothing in package.json — no npm script, no dependency;
 * `--no-install` means npx can only run the tsx already in node_modules, never download one. No
 * database is involved: the three catalogue files are read out of git with `git show`, then mapped
 * by the same tested reader the app uses.)
 *
 * Why this exists: the golden's numbers were recorded on the catalogue as committed in 7b2a499
 * (identical at tag v1.3). A board saved under Phase 11 carries its blank by value, so the tests
 * that replay those numbers must read these pinned blanks and not today's catalogue — which means
 * later catalogue corrections (quick 261001-v1q onward) never disturb them. The blanks kept are the
 * distinct vendor + name pairs the golden's cases name, sorted by vendor then name.
 *
 * The script prints, per blank, whether it still matches today's catalogue; that comparison only
 * affects what is printed, never the file. Running it twice writes the same bytes.
 */
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { rowsToBlankRecords } from "@/lib/blanks/catalog";
import { parseCsv } from "@/lib/blanks/csv";
import { readSeedCatalog, SEED_CSV_FILES } from "@/lib/blanks/seed-files";
import type { BlankRecord } from "@/lib/geometry/blank";
import golden from "@/lib/geometry/__fixtures__/phase11-foil-golden.json";

const PINNED_COMMIT = "7b2a499ea865eda826229bed8af25fdf594a7dc8";
const GOLDEN = "lib/geometry/__fixtures__/phase11-foil-golden.json";
const OUTPUT = path.resolve(process.cwd(), "lib/geometry/__fixtures__/phase11-foil-golden-blanks.json");
const PROVENANCE =
  "GENERATED by scripts/extract-phase11-golden-blanks.ts from db/seed/blanks/*.csv as committed in 7b2a499 " +
  "(the catalogue phase11-foil-golden.json was recorded on) — never hand-edit; re-run the script";

function pinnedCatalogue(): BlankRecord[] {
  return SEED_CSV_FILES.flatMap((file) => {
    const text = execFileSync("git", ["show", `${PINNED_COMMIT}:db/seed/blanks/${file}`], {
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024,
    });
    return rowsToBlankRecords(parseCsv(text), file);
  });
}

function main() {
  if (!existsSync(path.resolve(process.cwd(), GOLDEN))) {
    throw new Error(`Run this from the repository root (${GOLDEN} not found here).`);
  }
  const pinned = pinnedCatalogue();
  const today = readSeedCatalog();

  const wanted = new Map<string, { vendor: string; name: string }>();
  for (const entry of golden.cases) {
    wanted.set(`${entry.vendor}\u0000${entry.name}`, { vendor: entry.vendor, name: entry.name });
  }

  const kept: BlankRecord[] = [];
  for (const { vendor, name } of wanted.values()) {
    const record = pinned.find((blank) => blank.vendor === vendor && blank.name === name);
    if (!record) throw new Error(`${vendor} ${name} is not in the catalogue as committed in ${PINNED_COMMIT}.`);
    kept.push(record);
  }
  kept.sort((a, b) =>
    a.vendor !== b.vendor ? (a.vendor < b.vendor ? -1 : 1) : a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
  );

  let differ = 0;
  for (const record of kept) {
    const now = today.find((blank) => blank.vendor === record.vendor && blank.name === record.name);
    const same = now !== undefined && JSON.stringify(now) === JSON.stringify(record);
    if (!same) differ += 1;
    console.log(`${record.vendor} ${record.name}: ${same ? "same as today's catalogue" : "DIFFERS from today's catalogue"}`);
  }

  writeFileSync(OUTPUT, `${JSON.stringify({ provenance: PROVENANCE, blanks: kept }, null, 2)}\n`);
  console.log(`wrote ${path.relative(process.cwd(), OUTPUT)} (${kept.length} blanks, ${differ} differ from today's catalogue)`);
}

try {
  main();
} catch (error: unknown) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
