/**
 * GENERATED FILE PRODUCER — writes lib/geometry/__fixtures__/round-nose-golden.json: the founder's
 * chosen round nose (sketch 012, variant C, 2026-10-07: "C looks great and seems like the simplest
 * update too."), as the SKETCH ITSELF draws it, for every catalogue blank whose nose is printed 0
 * wide with a wider station before it (quick 261007-c3h, D8). The output is generated and must never
 * be hand-edited; re-run this script.
 *
 *   npx --no-install tsx --tsconfig ./tsconfig.json scripts/extract-round-nose-golden.ts
 *
 * run from the repository root. (Nothing in package.json — no npm script, no dependency;
 * `--no-install` means npx can only run the tsx already in node_modules, never download one. No
 * database is involved: the catalogue is read from the committed CSVs under db/seed/blanks/ through
 * the tested reader, `lib/blanks/seed-files.ts`.)
 *
 * It EXECUTES the sketch's own code — `reference/sketches/012-round-nose-curves.js`, a byte-for-byte
 * copy of the sketch's curves.js — so every number in the fixture is the sketch's output, never a
 * transcription of it: the script calls its `parabolaCoefficients` and `variantC` and records the
 * 48 samples `variantC` draws inside each rounded segment (evenly in the square root of the distance
 * from the tip, the tip last). It computes no curve of its own, and the only inch conversion it does
 * is `mmToInches` from lib/geometry/units.ts at full precision (CLAUDE.md Rule 2).
 *
 * What it records (fixture keys):
 * - `provenance`, `units`: where the numbers came from, and what they are measured in.
 * - `blanks`: for each affected blank — its vendor and name, the label of the last printed width
 *   station before the tip, `widths` (every printed width by value, so the test can tell if the
 *   catalogue moved), and `points` (the sketch's samples past that station, `{ xIn, widthIn }`, with
 *   the FULL width — twice the sketch's half-width).
 *
 * It refuses to record a blank the sketch would NOT round (no catalogue blank is like that, F3), so
 * the golden can never quietly record today's curve as a round one. Running it twice writes the same
 * bytes.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { readSeedCatalog } from "@/lib/blanks/seed-files";
import type { BlankRecord } from "@/lib/geometry/blank";
import { mmToInches } from "@/lib/geometry/units";

const OUT = path.resolve(process.cwd(), "lib/geometry/__fixtures__/round-nose-golden.json");
const REFERENCE = "reference/sketches/012-round-nose-curves.js";

/** The sketch's record shape: inches, widths null where the catalogue prints none. */
interface SketchRecord {
  vendor: string;
  name: string;
  lengthIn: number;
  stations: { label: string; fromTailIn: number; widthIn: number | null }[];
}

interface SketchCurves {
  variantC(record: SketchRecord): [number, number][];
  parabolaCoefficients(record: SketchRecord): {
    D: number;
    hw: number;
    mk: number;
    a: number;
    b: number;
    pointed: boolean;
  } | null;
}

const sketch = createRequire(path.join(process.cwd(), "package.json"))(
  path.resolve(process.cwd(), REFERENCE),
) as SketchCurves;

function toSketchRecord(record: BlankRecord): SketchRecord {
  return {
    vendor: record.vendor,
    name: record.name,
    lengthIn: mmToInches(record.lengthMm),
    stations: record.stations.map((station) => ({
      label: station.label,
      fromTailIn: mmToInches(station.fromTailMm),
      widthIn: station.widthMm === null ? null : mmToInches(station.widthMm),
    })),
  };
}

const blanks = [];
for (const record of readSeedCatalog()) {
  const printed = record.stations.filter((station) => station.widthMm !== null);
  if (printed.length < 2) continue;
  const tip = printed[printed.length - 1];
  const station = printed[printed.length - 2];
  if (tip.widthMm !== 0 || !(station.widthMm! > 0)) continue;

  const asSketch = toSketchRecord(record);
  const co = sketch.parabolaCoefficients(asSketch);
  if (!co || co.pointed) {
    throw new Error(`${record.vendor} ${record.name}: the sketch would not round this nose — the golden must not record today's curve as a round one`);
  }
  const stationIn = mmToInches(station.fromTailMm);
  const points = sketch
    .variantC(asSketch)
    .filter(([x]) => x > stationIn + 1e-9)
    .map(([x, halfWidth]) => ({ xIn: x, widthIn: 2 * halfWidth }));

  blanks.push({
    vendor: record.vendor,
    name: record.name,
    station: station.label,
    widths: printed.map((s) => ({ label: s.label, fromTailMm: s.fromTailMm, widthMm: s.widthMm })),
    points,
  });
}

const fixture = {
  provenance:
    "Generated by scripts/extract-round-nose-golden.ts, which runs the sketch's own variantC from reference/sketches/012-round-nose-curves.js (sketch 012, variant C, chosen by the founder on 2026-10-07). Never hand-edited.",
  units:
    "points: xIn is inches from the blank's tail tip and widthIn is the blank's FULL width in inches (the sketch's half-width, doubled). widths: millimetres, as the catalogue prints them.",
  blanks,
};

writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`Wrote ${blanks.length} blanks to ${path.relative(process.cwd(), OUT)}`);
