/**
 * GENERATED FILE PRODUCER — writes lib/blanks/preset-blanks.generated.json: which foam blank each of
 * the four presets opens in, and the catalogue rows of exactly those blanks (Phase 11, D-03,
 * RESEARCH Pitfall 4). The output is generated and must never be hand-edited; re-run this script.
 *
 *   npx --no-install tsx --tsconfig ./tsconfig.json scripts/generate-preset-blanks.ts
 *
 * (D-20: nothing in package.json — no npm script, no dependency; `--no-install` means npx can only
 * run the tsx already in node_modules, never download one. No database is involved: the catalogue
 * is read from the committed CSVs under db/seed/blanks/ through the tested reader,
 * `lib/blanks/seed-files.ts`.)
 *
 * For each preset in BOARD_PRESETS (lib/geometry/presets.ts):
 *  - a captured `blank: { vendor, name, placement }` in the preset wins, recorded as not provisional;
 *  - otherwise the provisional pick is `provisionalPresetPick` (lib/blanks/preset-blanks.ts) — the
 *    fitting blank closest in length to the preset's own length, ties to less spare centre foam, at
 *    its fitting placement closest to centre, with the default fit settings and the preset's own
 *    centre and tips.
 * The picked blanks' records are copied exactly as the reader returns them — raw catalogue rows,
 * never interpolated values — sorted by vendor then name. The script prints one line per preset and
 * fails loudly (exit 1) when a captured blank is not in the catalogue or nothing fits a preset.
 * Running it twice writes the same bytes.
 */
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { isPickable } from "@/lib/blanks/catalog";
import { readSeedCatalog } from "@/lib/blanks/seed-files";
import type { BlankRecord } from "@/lib/geometry/blank";
import { prepareBlank } from "@/lib/geometry/blank-fit";
import { BOARD_PRESETS, type BoardPreset } from "@/lib/geometry/presets";
import { formatPresetInches } from "@/lib/geometry/preset-source";
import { mmToInches, type Mm } from "@/lib/geometry/units";

const OUTPUT = path.resolve(process.cwd(), "lib/blanks/preset-blanks.generated.json");
const NOTE = "GENERATED by scripts/generate-preset-blanks.ts from db/seed/blanks/*.csv — never hand-edit; re-run the script";

interface Pick {
  vendor: string;
  name: string;
  placementMm: Mm;
  provisional: boolean;
}

function serialise(picks: Record<string, Pick>, blanks: BlankRecord[]): string {
  return `${JSON.stringify({ note: NOTE, picks, blanks }, null, 2)}\n`;
}

async function main() {
  if (!existsSync(path.resolve(process.cwd(), "lib/blanks/preset-blanks.ts"))) {
    throw new Error("Run this from the repository root (lib/blanks/preset-blanks.ts not found here).");
  }
  // lib/blanks/preset-blanks.ts imports the file this script writes; on a first run (or after it
  // was deleted) give it an empty module to import, then load the rule.
  if (!existsSync(OUTPUT)) writeFileSync(OUTPUT, serialise({}, []));
  const { provisionalPresetPick } = await import("@/lib/blanks/preset-blanks");

  const catalogue = readSeedCatalog();
  const prepared = catalogue.filter(isPickable).map(prepareBlank);

  const picks: Record<string, Pick> = {};
  const picked = new Map<string, BlankRecord>();
  const lines: string[] = [];
  for (const preset of BOARD_PRESETS as readonly BoardPreset[]) {
    let pick: Pick;
    if (preset.blank) {
      const { vendor, name, placement } = preset.blank;
      pick = { vendor, name, placementMm: placement, provisional: false };
    } else {
      const rule = provisionalPresetPick(preset, prepared);
      pick = { vendor: rule.vendor, name: rule.name, placementMm: rule.placementMm, provisional: true };
    }
    const record = catalogue.find((blank) => blank.vendor === pick.vendor && blank.name === pick.name);
    if (!record) throw new Error(`${preset.name}: ${pick.vendor} ${pick.name} is not in the blank catalogue.`);
    if (!isPickable(record)) throw new Error(`${preset.name}: ${pick.vendor} ${pick.name} is not a pickable blank.`);
    picks[preset.id] = pick;
    picked.set(`${record.vendor}\u0000${record.name}`, record);
    const placementIn = formatPresetInches(pick.placementMm);
    lines.push(
      `${preset.id}: ${pick.vendor} ${pick.name} at ${Math.round(pick.placementMm * 1000) / 1000} mm` +
        ` (${placementIn}" toward nose; blank ${mmToInches(record.lengthMm).toFixed(3)}" long)` +
        ` (${pick.provisional ? "provisional" : "captured"})`,
    );
  }

  const blanks = [...picked.values()].sort((a, b) =>
    a.vendor !== b.vendor ? (a.vendor < b.vendor ? -1 : 1) : a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
  );
  writeFileSync(OUTPUT, serialise(picks, blanks));
  for (const line of lines) console.log(line);
  console.log(`wrote ${path.relative(process.cwd(), OUTPUT)} (${blanks.length} blanks)`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
